version: "2"

services:
  nginx:
    image: "nginx:latest"
    ports:
          - 80:80
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php:php
#PHP
  php:
    build: ./nginx/php/
    volumes:
      - ./www:/usr/share/nginx/html
    links:
      - db:db
#MySQL
  db:
    image: "mysql"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
volumes:
    db_data:
